# Created by Braden Meyers, Jun 2025

services:
  cougars:
    image: frostlab/cougars:vehicle
    build: .
    container_name: cougars
    user: frostlab
    network_mode: host
    privileged: true
    volumes:
      - ../../bag:/home/frostlab/bag:rw
      - ../../config:/home/frostlab/config:rw
      - ../../cougars-ros2:/home/frostlab/ros2_ws
      - ../../cougars-teensy:/home/frostlab/teensy_ws
      - ../../cougars-gpio:/home/frostlab/gpio
      - ../../moos-ivp-extend:/home/frostlab/moos-ivp-extend
      - ./entrypoint.sh:/home/frostlab/entrypoint.sh
      - /etc/localtime:/etc/localtime:ro # Syncs the container's time with the host
      - /dev:/dev:rw
    entrypoint: /home/frostlab/entrypoint.sh
    restart: always  # Optional: Keeps the container running after exit unless you want it to be removed like with --rm