#!/bin/bash
# cougarsrc bashrc type script that will be sourced in every terminal
#
export LABNAME='frostlab'

source /home/$LABNAME/ros2_ws/install/setup.bash
export FASTRTPS_DEFAULT_PROFILES_FILE=/home/$LABNAME/config/fast_discovery_config.xml

# Defines RPi environment variables for use in Docker bash scripts
# - When setting up a new vehicle, do not directly edit the file in 'templates'; rather the copied file generated by 'setup.sh' in 'config'
# - If you edit this file, you'll need to make sure the copied file in 'config' is updated as well

export NAMESPACE=coug0 # ex. coug0
export VEHICLE_PARAMS_FILE=/home/frostlab/config/vehicle_params.yaml # ex. /home/frostlab/config/vehicle_params.yaml

export GPIO_CHIP=/dev/gpiochip0 # ex. /dev/gpiochip0

# Run "ifconfig eth0 | grep 'inet ' | awk '{print $2}'" from OUTSIDE THE DOCKER CONTAINER and copy that number (ex. "192.168.194.59") here
export STATIC_IP=0
export VEHICLE_ID=0

# Workspace directory of CoUGARS repository Should be sent to the local file when run on setup 
export COUG_WORKSPACE_DIR="/home/bjm255/couguv/CoUGARs"
