# Created by Braden Meyers, Jun 2025

services:
  cougars:
    image: frostlab/cougars:bluerov
    build: .
    container_name: cougars
    user: frostlab
    network_mode: host
    privileged: true
    volumes:
      - ../../bag:/home/frostlab/bag:rw
      - ../../config:/home/frostlab/config:rw
      - ../../cougars-ros2:/home/frostlab/ros2_ws
      - ../../oculus:/home/frostlab/oculus
      - ./entrypoint.sh:/home/frostlab/entrypoint.sh
      - /etc/localtime:/etc/localtime:ro # Syncs the container's time with the host
      - /dev:/dev:rw
      - /run/udev:/run/udev:ro  # Needed for microstrain driver to access devices??
      - ../.ssh_keys:/home/frostlab/.ssh     # Syncs ssh keys for the vehicles to clone from bitbucket
    entrypoint: /home/frostlab/entrypoint.sh
    restart: always  # Optional: Keeps the container running after exit unless you want it to be removed like with --rm